Docker
DucaturFw/ducor-frontend pull request #12
Opened 2018-08-06 12:51 UTC by Sindbag

Dockerfile for production, devapi and cypress runs

2018-08-06 14:12 UTC, zlumer requested changes
Let's stick to the following architecture:

1. Production docker image:
- builds app into static html with Webpack
- uses ENV vars to specify API `url` & `port` (and other variables)
- runs nginx on a specified port (not necessary 80)

2. Testing image:
- launches production docker container on e.g. port 3090; fails tests if webpack build fails
- launches dev-api (`yarn dev-api`)
- runs Cypress tests over production docker container

During development we will use `webpack-dev-server` for frontend development and run tests locally via `yarn dev-api` and `yarn test`.

2018-08-06 14:12 UTC, zlumer commented on package.json
> +    "server": "ts-node server/index.ts",
Remove `server` script completely with `server/index.ts`.
Node.js express server is now deprecated in favor of nginx.

2018-08-06 14:12 UTC, zlumer commented on Dockerfile
> +FROM nginx:1.15
👍

2018-08-06 14:12 UTC, zlumer commented on Dockerfile
> +EXPOSE 80
Port should be allowed to change from host machine by passing environment variable (or similar method)

2018-08-06 14:12 UTC, zlumer commented on Dockerfile-cypress
> +# base image
Test-only environment is not necessary to run in Docker container, let's remove this image.

2018-08-06 14:12 UTC, zlumer commented on Dockerfile-devapi
> +FROM keymetrics/pm2:8-alpine
Test-only environment is not necessary to run in separate Docker container, let's remove this image.

2018-08-06 14:12 UTC, zlumer commented on cypress/integration/simple.spec.ts
> +	let URL = `http://${Cypress.env('URL') || 'localhost'}:${Cypress.env('PORT') || '80'}`
Not necessary after removing Cypress-test image.

2018-08-06 14:12 UTC, zlumer commented on dev-api/index.js
> +module.exports = app.listen(process.env.DUCOR_API_PORT)
Revert, never needed to change.

2018-08-06 14:12 UTC, zlumer commented on package.json
> +    "ci": "yarn build && server-test test-serve \"$DUCOR_FRONT_PORT|$DUCOR_API_PORT/config\" test"
Revert, not needed after removing Cypress-test image.

2018-08-06 14:12 UTC, zlumer commented on webpack.dev.config.js
> +const getEnvKeys = () => {
Why not [dotenv-webpack](https://github.com/mrsteele/dotenv-webpack)?

2018-08-06 14:14 UTC, Sindbag commented on Dockerfile
> +EXPOSE 80
here we have default nginx.conf prod-ready from stage 0 contrainer, the port is hardcoded there, if we want to change it we have to maintain nginx.conf file

2018-08-06 14:20 UTC, Sindbag commented on Dockerfile-cypress
> +# base image
So do we agree on cypress run in docker for travis ci or remove it

2018-08-06 14:27 UTC, zlumer commented on Dockerfile-cypress
> +# base image
Let's keep it. Just patch the necessary functionality and add a testing docker-compose config.

2018-08-07 10:58 UTC, zlumer requested changes
Everything's okay, let's remove legacy code, fix `docker-compose down` and merge this.

2018-08-07 10:58 UTC, zlumer commented on webpack.dev.config.js
> +const getEnvKeys = () => {
As far as I can see, this code is no longer used.

2018-08-07 15:38 UTC, zlumer approved these changes
👍

2018-08-07 15:41 UTC, merged